import { Level } from "./types";

export const GRID_WIDTH = 8;
export const GRID_HEIGHT = 6;

export const levels: Level[] = [
  {
    id: 1,
    name: "Nivå 1 - Enkel start",
    items: [
      {
        id: "boklada",
        name: "Boklåda",
        color: "#1E5F99",
        cells: [[0, 0], [1, 0], [2, 0]],
        width: 3,
        height: 1,
      },
      {
        id: "lampa",
        name: "Lampa",
        color: "#E6F0FB",
        cells: [[0, 0], [0, 1], [0, 2]],
        width: 1,
        height: 3,
      },
      {
        id: "vaxter",
        name: "Växt",
        color: "#22C55E",
        cells: [[0, 0], [1, 0], [0, 1], [1, 1]],
        width: 2,
        height: 2,
      },
      {
        id: "kudde",
        name: "Kudde",
        color: "#F9A826",
        cells: [[0, 0], [1, 0]],
        width: 2,
        height: 1,
      },
    ],
  },
  {
    id: 2,
    name: "Nivå 2 - Mer utmaning",
    items: [
      {
        id: "skohylla",
        name: "Skohylla",
        color: "#1E5F99",
        cells: [[0, 0], [1, 0], [0, 1]],
        width: 2,
        height: 2,
      },
      {
        id: "boklada2",
        name: "Boklåda",
        color: "#174A77",
        cells: [[0, 0], [1, 0], [2, 0]],
        width: 3,
        height: 1,
      },
      {
        id: "lampa2",
        name: "Lampa",
        color: "#E6F0FB",
        cells: [[0, 0], [0, 1], [0, 2]],
        width: 1,
        height: 3,
      },
      {
        id: "vaxter2",
        name: "Växt",
        color: "#22C55E",
        cells: [[0, 0], [1, 0], [0, 1], [1, 1]],
        width: 2,
        height: 2,
      },
      {
        id: "kudde2",
        name: "Kudde",
        color: "#F9A826",
        cells: [[0, 0], [1, 0]],
        width: 2,
        height: 1,
      },
    ],
  },
  {
    id: 3,
    name: "Nivå 3 - Expert",
    items: [
      {
        id: "langsak",
        name: "Lång sak",
        color: "#1E5F99",
        cells: [[0, 0], [1, 0], [2, 0], [3, 0]],
        width: 4,
        height: 1,
      },
      {
        id: "skohylla2",
        name: "Skohylla",
        color: "#174A77",
        cells: [[0, 0], [1, 0], [0, 1]],
        width: 2,
        height: 2,
      },
      {
        id: "lampa3",
        name: "Lampa",
        color: "#E6F0FB",
        cells: [[0, 0], [0, 1], [0, 2]],
        width: 1,
        height: 3,
      },
      {
        id: "vaxter3",
        name: "Växt",
        color: "#22C55E",
        cells: [[0, 0], [1, 0], [0, 1], [1, 1]],
        width: 2,
        height: 2,
      },
      {
        id: "kudde3",
        name: "Kudde",
        color: "#F9A826",
        cells: [[0, 0], [1, 0]],
        width: 2,
        height: 1,
      },
      {
        id: "liten",
        name: "Liten sak",
        color: "#64748B",
        cells: [[0, 0]],
        width: 1,
        height: 1,
      },
    ],
  },
  {
    id: 4,
    name: "Nivå 4 - Mästare",
    items: [
      {
        id: "langsak2",
        name: "Lång sak",
        color: "#1E5F99",
        cells: [[0, 0], [1, 0], [2, 0], [3, 0]],
        width: 4,
        height: 1,
      },
      {
        id: "skohylla3",
        name: "Skohylla",
        color: "#174A77",
        cells: [[0, 0], [1, 0], [0, 1]],
        width: 2,
        height: 2,
      },
      {
        id: "lampa4",
        name: "Lampa",
        color: "#E6F0FB",
        cells: [[0, 0], [0, 1], [0, 2]],
        width: 1,
        height: 3,
      },
      {
        id: "vaxter4",
        name: "Växt",
        color: "#22C55E",
        cells: [[0, 0], [1, 0], [0, 1], [1, 1]],
        width: 2,
        height: 2,
      },
      {
        id: "kudde4",
        name: "Kudde",
        color: "#F9A826",
        cells: [[0, 0], [1, 0]],
        width: 2,
        height: 1,
      },
      {
        id: "liten2",
        name: "Liten sak",
        color: "#64748B",
        cells: [[0, 0]],
        width: 1,
        height: 1,
      },
      {
        id: "liten3",
        name: "Liten sak",
        color: "#94A3B8",
        cells: [[0, 0]],
        width: 1,
        height: 1,
      },
    ],
  },
];

